[versions]
android = "8.1.0"
hiltAndroid = "2.44"
junit = "4.13.2"
kotlin = "1.8.10"
kotlinxCoroutinesAndroid = "1.6.4"
lifecycleLivedataKtx = "2.5.1"
moshi = "1.14.0"
navigationFragmentKtx = "2.5.3"
okhttp = "4.12.0"
uiAndroid = "1.5.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.0" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version = "1.6.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.4" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version = "1.1.2" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.7.6" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "uiAndroid" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiAndroid" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiAndroid" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.18.0" }
commons-validator = { module = "commons-validator:commons-validator", version = "1.10.0" }
core-ktx = { module = "androidx.test:core-ktx", version = "1.5.0" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hiroaki-core = { module = "me.jorgecastillo:hiroaki-core", version = "0.2.3" }
json = { module = "org.json:json", version = "20220924" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.1" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version = "4.10.0" }
material = { module = "com.google.android.material:material", version = "1.7.0" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.8.0" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "4.1.0" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "4.9.3" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version = "4.10.3" }

[plugins]
android-application = { id = 'com.android.application', version.ref = 'android' }
android-library = { id = 'com.android.library', version.ref = 'android' }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = "kotlin" }
com-diffplug-spotless = { id = "com.diffplug.spotless", version = "6.11.0" }
androidx-navigation-safeargs-kotlin = { id = 'androidx.navigation.safeargs.kotlin', version="2.5.3" }
gradle-nexus-publish-plugin = { id = 'io.github.gradle-nexus.publish-plugin', version = '2.0.0' }
jetbrains-kotlinx-kover = { id = 'org.jetbrains.kotlinx.kover', version = '0.6.1' }
jetbrains-dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version = "1.8.10-1.0.9" }
dagger-hilt-android = { id = 'com.google.dagger.hilt.android', version = '2.44' }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
