name: Alert

on:
  workflow_run:
    workflows: ['CI']
    types: ['completed']
    branches: ['main']

jobs:
  send-alert:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send alert to slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "message": "CI failed on main branch in android-pos-terminal-sdk! https://github.com/Forage-PCI-CDE/android-pos-terminal-sdk/actions"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_POS }}
