name: Alert Slack on QA-Test failure

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  send-alert:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Send alert to slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "message": "CI failed on main branch in forage-android-sdk!",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
