name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests for the sandboxDebug build
        run: ./gradlew testSandboxDebugUnitTest --stacktrace

      - name: Check spotless
        run: ./gradlew spotlessCheck

      - name: Build all build variants
        run: ./gradlew assemble --stacktrace

      - name: Upload build outputs (APKs and SDK AARs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: |
            sample-app/build/outputs/
            forage-android/build/outputs/