name: Lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: forage-android:lint
      - uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: forage-android/build/reports/lint-results-certDebug.sarif
          category: lint-forage-android