name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build AAR
        run: ./gradlew build -x test

      - name: Build POM file + Gradle Metadata
        run: ./gradlew publishToMavenLocal

      - name: Create release with the tag name and attach AAR, pom.xml, and gradle metadata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes

          gh release upload "$tag" \
              ./forage-android/build/outputs/aar/forage-android-release.aar
          
          gh release upload "$tag" \
              ./forage-android/build/publications/release/pom-default.xml

          gh release upload "$tag" \
              ./forage-android/build/publications/release/metadata.json
          
